name: BS

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.step1.outputs.myoutput }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Dotnet
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: '7.0.x'
    - name: Install Trash
      shell: bash
      run: |
        dotnet tool restore
    - name: Create local changes
      if: github.ref == 'refs/heads/master'
      continue-on-error: false
      run: |
        if [ "${{github.event_name}}" == "pull_request" ]; then
          Before="${{github.event.pull_request.base.sha}}"
          After="${{github.event.pull_request.head.sha}}"
        else
          Before="${{github.event.before}}"
          After="${{github.event.after}}"
        fi
        bash _scripts/reformat.sh -f diff $Before $After
    - name: Push changes
      uses: ad-m/github-push-action@master
      if: github.ref == 'refs/heads/master'
      continue-on-error: false
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: Gather targets.
      id: step1
      shell: bash
      run: |
        if [ "${{github.event_name}}" == "pull_request" ]; then
          Before="${{github.event.pull_request.base.sha}}"
          After="${{github.event.pull_request.head.sha}}"
        else
          Before="${{github.event.before}}"
          After="${{github.event.after}}"
        fi
        bash _scripts/what-to-test.sh $Before $After >> $GITHUB_OUTPUT

